import type { Gun } from './gunSchema'

const imageBaseUrl =
  'https://raw.githubusercontent.com/pubg/api-assets/master/Assets/Item/Weapon/Main'

export const fakeGunsData: Gun[] = [
  {
    id: 1,
    name: 'AKM',
    role: 'Powerful Standard AR',
    description:
      'The AKM is reliable, deals high damage, and is ideal for powerful close- and mid-range engagements.',
    bullets: [
      'High Damage',
      'Consistent Accuracy',
      'Great for Aggressive Playstyles',
    ],
    image: `${imageBaseUrl}/Item_Weapon_AK47_C.png`,
    damage: 82,
    range: 68,
    recoil: 78,
    fireRate: 60,
    magazineSize: 30,
    ammoType: '7.62 mm',
  },
  {
    id: 2,
    name: 'M16A4',
    role: 'Versatile All-Rounder',
    description:
      'The M16A4 is one of the most versatile weapons in the game and is perfect for controlled and precise gameplay.',
    bullets: [
      'Good Accuracy',
      'Fast Follow-Up Shots',
      'Highly Versatile',
    ],
    image: `${imageBaseUrl}/Item_Weapon_M16A4_C.png`,
    damage: 67,
    range: 76,
    recoil: 52,
    fireRate: 72,
    magazineSize: 30,
    ammoType: '5.56 mm',
  },
  {
    id: 3,
    name: 'UMP45',
    role: 'Perfect for Close Quarters',
    description:
      'The UMP45 offers a fast rate of fire and excellent control during intense close-range fights.',
    bullets: [
      'Fast Fire Rate',
      'Strong at Close Range',
      'Easy Recoil Control',
    ],
    image: `${imageBaseUrl}/Item_Weapon_UMP_C.png`,
    damage: 52,
    range: 42,
    recoil: 35,
    fireRate: 76,
    magazineSize: 25,
    ammoType: '.45 ACP',
  },
  {
    id: 4,
    name: 'AWM',
    role: 'Long-Range Powerhouse',
    description:
      'The AWM is the perfect choice for players who want to dominate long-range battles with precision and deadly power.',
    bullets: [
      'Extreme Long-Range Damage',
      'Very High Precision',
      'Powerful Sniper Rifle',
    ],
    image: `${imageBaseUrl}/Item_Weapon_AWM_C.png`,
    damage: 100,
    range: 100,
    recoil: 88,
    fireRate: 18,
    magazineSize: 5,
    ammoType: '.300 Magnum',
  },
  {
    id: 5,
    name: 'MP5K',
    role: 'Fast, Compact, and Effective',
    description:
      'The MP5K is ideal for quick weapon handling, tight spaces, and aggressive pushes.',
    bullets: [
      'Very Fast Fire Rate',
      'Great for Quick Duels',
      'Easy to Control',
    ],
    image: `${imageBaseUrl}/Item_Weapon_MP5K_C.png`,
    damage: 45,
    range: 38,
    recoil: 30,
    fireRate: 86,
    magazineSize: 30,
    ammoType: '9 mm',
  },
  {
    id: 6,
    name: 'Kar98k',
    role: 'Classic Precision Rifle',
    description:
      'The Kar98k is a reliable and precise weapon for landing powerful shots over long distances.',
    bullets: [
      'High Precision',
      'Powerful Single Shot',
      'Excellent at Long Range',
    ],
    image: `${imageBaseUrl}/Item_Weapon_Kar98k_C.png`,
    damage: 88,
    range: 92,
    recoil: 82,
    fireRate: 14,
    magazineSize: 5,
    ammoType: '7.62 mm',
  },
  {
    id: 7,
    name: 'M24',
    role: 'Reliable Sniper Rifle',
    description:
      'The M24 is perfect for careful and precise players who want to control the battlefield from a distance.',
    bullets: [
      'Very High Accuracy',
      'Excellent Range',
      'Reliable Long-Range Performance',
    ],
    image: `${imageBaseUrl}/Item_Weapon_M24_C.png`,
    damage: 92,
    range: 96,
    recoil: 84,
    fireRate: 16,
    magazineSize: 5,
    ammoType: '7.62 mm',
  },
  {
    id: 8,
    name: 'Vector',
    role: 'Rapid-Fire SMG',
    description:
      'The Vector is an extremely fast close-range weapon for aggressive pushes and quick encounters.',
    bullets: [
      'Very High Fire Rate',
      'Excellent in Close Combat',
      'Great for Fast Reactions',
    ],
    image: `${imageBaseUrl}/Item_Weapon_Vector_C.png`,
    damage: 42,
    range: 30,
    recoil: 38,
    fireRate: 96,
    magazineSize: 19,
    ammoType: '9 mm',
  },
  {
    id: 9,
    name: 'P90',
    role: 'Compact and Reliable',
    description:
      'The P90 offers a large magazine capacity and reliable control during intense combat situations.',
    bullets: [
      'Large Magazine Capacity',
      'Great for Sustained Fire',
      'Very Stable',
    ],
    image: `${imageBaseUrl}/Item_Weapon_P90_C.png`,
    damage: 48,
    range: 50,
    recoil: 28,
    fireRate: 90,
    magazineSize: 50,
    ammoType: '5.7 mm',
  },
  {
    id: 10,
    name: 'S12K',
    role: 'Close-Range Shotgun',
    description:
      'The S12K delivers devastating power in tight spaces and can eliminate enemies within seconds.',
    bullets: [
      'Powerful Close-Range Damage',
      'Effective in Tight Spaces',
      'Ideal for Surprise Attacks',
    ],
    image: `${imageBaseUrl}/Item_Weapon_Saiga12_C.png`,
    damage: 90,
    range: 22,
    recoil: 72,
    fireRate: 48,
    magazineSize: 5,
    ammoType: '12 Gauge',
  },
]